- name: Install Kubectl
  dnf:
    name: kubectl-1.30.*
    state: present
    allow_downgrade: yes  # Permet les downgrades si nécessaire
- name: Initialize Kubernetes Cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Set KUBECONFIG environment variable for Master
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
  args:
    executable: /bin/bash

- name: Configure kubectl for the Current User
  shell: |
    mkdir -p $HOME/.kube
    sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  args:
    executable: /bin/bash

- name: Install Flannel CNI Plugin
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  when: inventory_hostname == groups['master'][0]

- name: Get Kubeadm Join Command
  command: kubeadm token create --print-join-command
  register: join_command
  changed_when: false

- name: Set kubeadm_join_command for all hosts
  set_fact:
    kubeadm_join_command: "{{ join_command.stdout }}"





- name: Restart kubelet on Master
  service:
    name: kubelet
    state: restarted
