---
# Tâches pour installer et configurer ArgoCD sur Kubernetes

- name: Créer namespace argocd
  command: kubectl create namespace argocd
  ignore_errors: yes

- name: Installer ArgoCD
  command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Patcher le service argocd-server pour type NodePort
  shell: |
    kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "NodePort"}}'
  ignore_errors: yes


