# ------------------------------
# Installer Node Exporter sur les VMs Azure
# ------------------------------
- name: Installer Node Exporter sur les VMs Azure
  import_tasks: azuremono.yml
  when: "'azure_vms' in group_names"

# ------------------------------
# Installer monitoring complet du cluster Kubernetes
# ------------------------------
- name: Installer monitoring Kubernetes
  import_tasks: monitoring.yml
  when: "'master' in group_names"


