# roles/devops/tasks/main.yml

# ------------------------------
# Kubernetes commun (master + workers uniquement)
# ------------------------------
- name: "Installation de Kubernetes"
  import_tasks: commun.yml
  when: "'kubernetes' in group_names"

# ------------------------------
# Configurer le Master Kubernetes
# ------------------------------
- name: Configurer le Master Kubernetes
  import_tasks: master.yml
  when: "'master' in group_names"

# ------------------------------
# Configurer les Workers Kubernetes
# ------------------------------
- name: Configurer les Workers Kubernetes
  import_tasks: workers.yml
  when: "'workers' in group_names"


